#!/bin/sh

SERV_TYPE_START="START"
SERV_TYPE_BASE="BASE"
SERV_TYPE_3RD="3RD"
SERV_TYPE_DONE="DONE"
SERV_TYPE_STOP="STOP"
SERV_TYPE_RESTART="RESTART"

SERV_TYPE_MON="MON"
SERV_TYPE_OTHER="OTHER"
SERV_TYPE_MUST="MUST"

HA_PREFIX="/usr/syno/synoha"

USER_INITD_DIR=/usr/local/etc/rc.d/
